---
title: "STAT2202 Final Project Graphs"
output: html_document
---

```{r}
library(ggplot2)
library(reshape2)
library(RColorBrewer)
library(rugarch)
library(rmgarch)
library(RQuantLib)
library(quadprog)
library(quantmod)
```

```{r}
source("../SDAFE2.R")
```

```{r}
getStackedPlot <- function (path) {
  prices_index_weights = read.csv(path)
  
  QUARTERS <- c("2017-06-30", "2017-09-29", "2017-12-29", "2018-03-29", "2018-06-29", "2018-09-28", 
                "2018-12-31", "2019-03-29", "2019-06-28", "2019-09-30")
  
  prices_index_weights_q = prices_index_weights[prices_index_weights$Date %in% QUARTERS, ]
  
  prices_index_weights_melt = melt(prices_index_weights_q[, 2:length(colnames(prices_index_weights_q))], id.vars="Date")
  
  prices_index_weights_plot <- ggplot() + 
    geom_bar(aes(y = value, x = Date, fill = variable), 
             data = prices_index_weights_melt, stat="identity", position="stack") + 
    ylab("Percent weights") + 
    xlab("Quarters") + 
    ggtitle("Portfolio Weights")
  
  prices_index_weights_plot+scale_fill_brewer(palette="Paired")
}

getStackedPlot("../data/prices_index_weights.csv")
```


```{r}
getStackedPlot("../data/price_diffs_index_weights.csv")
```


```{r}
getStackedPlot("../data/log_returns_index_weights.csv")
```


```{r}
agriculture_indicies <- read.csv("../data/agriculture_indicies.csv")
agriculture_indicies_out_of_sample <- read.csv("../data/agriculture_indicies_out_of_sample.csv")

plot(agriculture_indicies$Date, agriculture_indicies$Index_prices, type="b", col="black", lwd=2, xlab="Quarter", ylab="Index Price")
lines(agriculture_indicies$Date, agriculture_indicies$Index_price_diffs, type="l", col="red", lwd=2)
lines(agriculture_indicies$Date, agriculture_indicies$Index_log_returns, type="l", col="blue", lwd=2)

title("Index Price Change")
legend("topleft", c("Price", "Price Change", "Log Return"), lty = c(1, 1, 1), lwd=2, col=c("black", "red", "blue"))
```
```{r}
plot(agriculture_indicies_out_of_sample$Date, agriculture_indicies_out_of_sample$Index_prices, type="b", col="black", lwd=2, xlab="Quarter", ylab="Index Price")
lines(agriculture_indicies_out_of_sample$Date, agriculture_indicies_out_of_sample$Index_price_diffs, type="l", col="red", lwd=2)
lines(agriculture_indicies_out_of_sample$Date, agriculture_indicies_out_of_sample$Index_log_returns, type="l", col="blue", lwd=2)

title("Index Price Change - Out of Sample Data")
legend("topleft", c("Price", "Price Change", "Log Return"), lty = c(1, 1, 1), lwd=2, col=c("black", "red", "blue"))
```

```{r}
place_holder = rep(NA, length(agriculture_indicies$Date) - length(agriculture_indicies_out_of_sample$Date))
start_diff = agriculture_indicies$Index_prices[length(place_holder) + 1] -
  agriculture_indicies_out_of_sample$Index_prices[1]

plot(agriculture_indicies$Date, agriculture_indicies$Index_prices, 
     type="l", col="black", lwd=2, xlab="Quarter", ylab="Index Price", 
     ylim = c(100, 160))
lines(c(place_holder, agriculture_indicies_out_of_sample$Index_prices + start_diff), type="l", col="red", lwd=2)

title("Index price based on raw price - Complete series vs. out-of-sample data")
legend("topleft", c("Complete", "Out of sample"), lty = c(1, 1), lwd=2, col=c("black", "red"))
```

```{r}
place_holder = rep(NA, length(agriculture_indicies$Date) - length(agriculture_indicies_out_of_sample$Date))
start_diff = agriculture_indicies$Index_price_diffs[length(place_holder) + 1] -
  agriculture_indicies_out_of_sample$Index_price_diffs[1]

plot(agriculture_indicies$Date, agriculture_indicies$Index_price_diffs, 
     type="l", col="black", lwd=2, xlab="Quarter", ylab="Index Price", 
     ylim = c(100, 160))
lines(c(place_holder, agriculture_indicies_out_of_sample$Index_price_diffs + start_diff), type="l", col="red", lwd=2)

title("Index price based on price change - Complete series vs. out-of-sample data")
legend("topleft", c("Complete", "Out of sample"), lty = c(1, 1), lwd=2, col=c("black", "red"))
```


```{r}
place_holder = rep(NA, length(agriculture_indicies$Date) - length(agriculture_indicies_out_of_sample$Date))
start_diff = agriculture_indicies$Index_log_returns[length(place_holder) + 1] -
  agriculture_indicies_out_of_sample$Index_log_returns[1]

plot(agriculture_indicies$Date, agriculture_indicies$Index_log_returns, 
     type="l", col="black", lwd=2, xlab="Quarter", ylab="Index Price", 
     ylim = c(100, 160))
lines(c(place_holder, agriculture_indicies_out_of_sample$Index_log_returns + start_diff), type="l", col="red", lwd=2)

title("Index price based on log return - Complete series vs. out-of-sample data")
legend("topleft", c("Complete", "Out of sample"), lty = c(1, 1), lwd=2, col=c("black", "red"))
```


```{r}
QUARTERS <- as.Date(c("2016-12-31", "2017-03-31", "2017-06-30", "2017-09-30", "2017-12-31", "2018-03-31", 
                      "2018-06-30", "2018-09-30", "2018-12-31", "2019-03-31", "2019-06-30", "2019-09-30"))

LEAD_IN <- 2

prices_index_weights = read.csv("../data/prices_index_weights.csv")
assets = colnames(prices_index_weights)[3:14]
assets[c(1, 5, 9)] # Pick three

get_cor <- function (i) {
  fit <- readRDS(paste0("../models/dcc fits/prices_", QUARTERS[i]))
  
  return(rcor(fit))
}

get_forecast <- function (i) {
  fit <- readRDS(paste0("../models/dcc fits/prices_", QUARTERS[i]))
  forecast_horizon <- sum(isBusinessDay(calendar="UnitedStates/NYSE", 
                                        dates=seq(QUARTERS[i], QUARTERS[i+1], by="day")))
  sim <- dccforecast(fit, n.ahead = forecast_horizon)
  
  return(sim)
}
```

```{r}
fit <- readRDS(paste0("../models/dcc fits/prices_", QUARTERS[3]))
fit
```

```{r}
i = 3
cor_mat = get_cor(i)
par(mfrow = c(3, 1))
plot(as.xts(cor_mat[1, 5, ]), xlab="Correlation", ylab="Quarter", main="Correlation changes over time - USD & BTC")
plot(as.xts(cor_mat[1, 9, ]), xlab="Correlation", ylab="Quarter", main="Correlation changes over time - USD & X__W_USSD")
plot(as.xts(cor_mat[5, 9, ]), xlab="Correlation", ylab="Quarter", main="Correlation changes over time - BTC & X__W_USSD")
```


```{r}
i = 3
forecast_i <- get_forecast(i)
R_forecast <- forecast_i@mforecast$R[[1]]
# 64, 125

d = c(125, 64)
usd_btc <- as.xts(cor_mat[1, 5, ])
my_periodicity <- unclass(periodicity(usd_btc))$label

v_dates_end <- seq(as.Date(end(usd_btc)),
                   by = my_periodicity,
                   length.out = (d[2]+1))[-1]
x_expand_time_index <- xts(rep(as.numeric(NA), d[2]), order.by = c(v_dates_end))

usd_btc_c <- c(usd_btc, x_expand_time_index)

f_usd_btc <- R_forecast[1, 5, ]

f_usd_btc_c <- xts(c(rep(NA, d[1]), f_usd_btc), order.by=index(usd_btc_c))

plot(usd_btc_c, xlab="Correlation", ylab="Quarter", main="Correlation changes over time - USD & BTC")
lines(f_usd_btc_c, type="b", col="red")
```

```{r}
usd_agri <- as.xts(cor_mat[1, 9, ])
my_periodicity <- unclass(periodicity(usd_agri))$label

v_dates_end <- seq(as.Date(end(usd_agri)),
                   by = my_periodicity,
                   length.out = (d[2]+1))[-1]
x_expand_time_index <- xts(rep(as.numeric(NA), d[2]), order.by = c(v_dates_end))

usd_agri_c <- c(usd_agri, x_expand_time_index)

f_usd_agri <- R_forecast[1, 9, ]

f_usd_agri_c <- xts(c(rep(NA, d[1]), f_usd_agri), order.by=index(usd_agri_c))

plot(usd_agri_c, xlab="Correlation", ylab="Quarter", main="Correlation changes over time - USD & Agri")
lines(f_usd_agri_c, type="b", col="red")
```

```{r}
btc_agri <- as.xts(cor_mat[5, 9, ])
my_periodicity <- unclass(periodicity(btc_agri))$label

v_dates_end <- seq(as.Date(end(btc_agri)),
                   by = my_periodicity,
                   length.out = (d[2]+1))[-1]
x_expand_time_index <- xts(rep(as.numeric(NA), d[2]), order.by = c(v_dates_end))

btc_agri_c <- c(btc_agri, x_expand_time_index)

f_btc_agri <- R_forecast[5, 9, ]

f_btc_agri_c <- xts(c(rep(NA, d[1]), f_btc_agri), order.by=index(btc_agri_c))

plot(btc_agri_c, xlab="Correlation", ylab="Quarter", main="Correlation changes over time - BTC & Agri")
lines(f_btc_agri_c, type="b", col="red")
```

```{r}
get_mLjungBox <- function (path) {
  agriculture_prices <- read.csv(path)
  return(mLjungBox(agriculture_prices[, 2: length(colnames(agriculture_prices))], lag=5))
}

get_mLjungBox("../data/agriculture_prices.csv")
```


```{r}
get_mLjungBox("../data/agriculture_price_diffs.csv")
```


```{r}
get_mLjungBox("../data/agriculture_log_returns.csv")
```

```{r}
QUARTERS <- as.Date(c("2016-12-31", "2017-03-31", "2017-06-30", "2017-09-30", "2017-12-31", "2018-03-31", 
                      "2018-06-30", "2018-09-30", "2018-12-31", "2019-03-31", "2019-06-30", "2019-09-30"))
model_12 <- readRDS(paste0("../models/dcc fits/prices_", QUARTERS[12]))
mLjungBox(residuals(model_12), lag=5)
```

 [1] "Date"          "USD"           "EURUSD"        "JPYUSD"        "CYNUSD"        "BTC"          
 [7] "ETH"           "XRP"           "XMR"           "X__W_USSD"     "X__SYB_TD"     "X_ICXD"       
[13] "CHRIS.CME_LB1"
```{r}
i_usd=2
i_btc=6
i_xwussd=10

get_acf_ccf <- function (path, i, j) {
  agriculture_prices <- read.csv(path)
  par(mfrow = c(2, 2))
  par(mar=c(3, 4, 3, 4))
  acf(agriculture_prices[, i], main=colnames(agriculture_prices)[i], ylab="ACF")
  ccf(agriculture_prices[, i], agriculture_prices[, j],
      main=paste(colnames(agriculture_prices)[i], "& ", colnames(agriculture_prices)[j]),
      ylab="CCF")
  ccf(agriculture_prices[, j], agriculture_prices[, i],
      main=paste(colnames(agriculture_prices)[j], "& ", colnames(agriculture_prices)[i]),
      ylab="CCF")
  acf(agriculture_prices[, j], main=colnames(agriculture_prices)[i], ylab="ACF")
}

get_acf_ccf("../data/agriculture_prices.csv", i_usd, i_btc)
```


```{r}
get_acf_ccf("../data/agriculture_prices.csv", i_usd, i_xwussd)
```


```{r}
get_acf_ccf("../data/agriculture_prices.csv", i_btc, i_xwussd)
```

```{r}
get_acf_ccf_residuals <- function (qu, i, j) {
  QUARTERS <- as.Date(c("2016-12-31", "2017-03-31", "2017-06-30", "2017-09-30", "2017-12-31", "2018-03-31", 
                      "2018-06-30", "2018-09-30", "2018-12-31", "2019-03-31", "2019-06-30", "2019-09-30"))
  model_fit <- readRDS(paste0("../models/dcc fits/prices_", QUARTERS[qu]))
  res = residuals(model_fit)
  series1 = as.numeric(res[, i])
  series2 = as.numeric(res[, j])
  
  par(mfrow = c(3, 2))
  par(mar=c(3, 4, 3, 4))
  acf(series1, main=colnames(res)[i], ylab="ACF")
  pacf(series1, main=colnames(res)[i], ylab="PACF")
  ccf(series1, series2,
      main=paste(colnames(res)[i], "& ", colnames(res)[j]),
      ylab="CCF")
  ccf(series2, series1,
      main=paste(colnames(res)[j], "& ", colnames(res)[i]),
      ylab="CCF")
  acf(series2, main=colnames(res)[i], ylab="ACF")
  pacf(series2, main=colnames(res)[i], ylab="PACF")
}

i_usd=1
i_btc=5
i_xwussd=9

get_acf_ccf_residuals(12, i_usd, i_btc)
```


```{r}
get_acf_ccf_residuals(12, i_usd, i_xwussd)
```

```{r}
get_acf_ccf_residuals(12, i_btc, i_xwussd)
```

```{r}
i_usd=2
i_btc=6
i_xwussd=10

get_initial_ts_plots <- function (i) {
  path1 = "../data/agriculture_prices.csv"
  path2 = "../data/agriculture_price_diffs.csv"
  path3 = "../data/agriculture_log_returns.csv"
  agriculture_prices <- read.csv(path1)
  agriculture_price_diffs <- read.csv(path2)
  agriculture_log_returns <- read.csv(path3)
  dates = as.Date(agriculture_prices$Date)
  
  par(mfrow = c(2, 2))
  par(mar=c(3, 4, 3, 4))
  plot(ts(agriculture_prices[i]), 
       type = "l", lty=1, lwd=1, 
       main=colnames(agriculture_prices)[i], 
       xaxt="n", ylab="price")
  axis(side=1,at=c(1, 300, 600),labels=c(dates[1], dates[300], dates[600]))
  
  plot(ts(agriculture_price_diffs[i]),
       main=colnames(agriculture_price_diffs)[i], 
       xaxt="n", ylab="price change", type = "l", lty=1, lwd=0.8)
  axis(side=1,at=c(1, 300, 600),labels=c(dates[1], dates[300], dates[600]))
  
  plot(ts(agriculture_log_returns[i]),
       main=colnames(agriculture_log_returns)[i], 
       xaxt="n", ylab="log return", type = "l", lty=1, lwd=0.8)
  axis(side=1,at=c(1, 300, 600),labels=c(dates[1], dates[300], dates[600]))
}

get_initial_ts_plots(i_usd)
```


```{r}
get_initial_ts_plots(i_btc)
```

```{r}
get_initial_ts_plots(i_xwussd)
```

Univariate

```{r}
library("forecast")
library("rugarch")
cols <- colnames(read.csv("../data/agriculture_prices.csv"))
cols
```

```{r}
ugarch_spec_USD <- readRDS(paste0("../models/specs/ugarch_", "prices_", cols[2]))
price_data = read.csv("../data/agriculture_prices.csv")
ugarch_USD = ugarchfit(spec=ugarch_spec_USD, data=price_data[, 2], )
ugarch_spec_USD
ugarch_USD
```

```{r}
Box.test(price_data[, 2], lag = 5, type = "Ljung-Box")
```

```{r}
library(MASS)
library(fGarch)
ugarch_spec_USD <- readRDS(paste0("../models/specs/ugarch_", "prices_", cols[2]))
price_data = read.csv("../data/agriculture_prices.csv")
ugarch_USD = ugarchfit(spec=ugarch_spec_USD, data=price_data[, 2], )

e <- residuals(ugarch_USD)
fit_normal <- fitdistr(e, "normal")
est_normal <- fit_normal$estimate
fit_normal

par(mfrow=c(1, 2))
plot(density(e), main = "Density Estimator Overlay")
lines(seq(-10, 10,0.01), dnorm(seq(-10, 10, 0.01),
                              mean = est_normal[1], sd = est_normal[2], log = FALSE),
      lty = 2 , col = 2 )
legend("topright", col = c(1,2), lty = c(1,2), legend = c("KDE", "Normal"), cex=0.75)
plot(qqnorm(e, datax = TRUE), main="QQ Plot")
```


```{r}
e <- residuals(ugarch_USD)
fit_t <- stdFit(e)
est_t <- fit_t$par
fit_t

par(mfrow=c(1, 2))
plot(density(e), main = "Density Estimator Overlay")
lines(seq(-10, 10,0.01), dstd(seq(-10, 10, 0.01),
                              mean = est_t[1], sd = est_t[2],
                              nu = est_t[3], log = FALSE),
      lty = 2 , col = 2 )
legend("topright", col = c(1,2), lty = c(1,2), legend = c("KDE", "T"), cex=0.75)
plot(qqnorm(e, datax = TRUE), main="QQ Plot")
```


```{r}
```


```{r}
```


```{r}
```

THE END.